project:
  type: book
  output-dir: _book

book:
  title: "Expeditionary Innovation"
  reader-mode: true

  page-footer:
    left: |
      _Expeditionary Innovation_ was written by Nile Hatch.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
# cover-image: cassia_crossbill_2.jpg
  site-url: https://ei.nilehatch.com/
  repo-url: https://github.com/nilehatch/exp_innov/
#  page-navigation: true
#  bread-crumbs: true
#  search: true

  chapters:
    - index.qmd
    - Expeditionary_Innovation.qmd
    - Organize_Team.qmd
    - Choose_People.qmd
    - Explore_Community.qmd
    - Hypothesize_Pain.qmd
    - Validate_Pain.qmd
    - Ideate_Solutions.qmd
    - Hypothesize_Solution.qmd
    - Test_Solution.qmd
    - Conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#    code-fold: true
#    code-link: true
    number-sections: true
    number-depth: 2
#    embed-resources: true

editor: source

execute:
  echo: false
