[build]
  publish = "_book"
  command = """
    wget -qO- https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb > quarto.deb && \
    sudo dpkg -i quarto.deb && \
    quarto render .
  """
  # Replace {quarto_version} with the desired version number, e.g., "1.1.189"

# [build.environment]
#   ENV_NAME = "value"
# Uncomment and replace ENV_NAME and value with your environment variables if needed

